# -*- coding: utf-8 -*-
"""BOJ_2309

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EbGpXQKY9DpUV7rCcQcbHqpPBh9K6nIg
"""

height = []
for i in range(9):
    height.append(int(input()))

height.sort()
f = 0
for i in range(9):
    for j in range(i+1, 9):
        new_h = []
        for k in range(9):
            if k != i and k!= j:
                new_h.append(height[k])
        if sum(new_h) == 100:
            print(*new_h, sep='\n')
            f = 1
            break
    if f:
        break