# -*- coding: utf-8 -*-
"""BOJ_3109.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RazEWsh25EqQ-TDfK8K23rdySxP7tLoH
"""

import sys
# input = sys.stdin.readline

def dfs(a,b,r,c):
    if b == c-1:
        return 1

    for i in range(3):
        new_a = a + move[i]
        new_b = b + 1

        if new_a < 0 or new_a >= r or new_b >= c or pipe[new_a][new_b] != '.' :
            continue
        pipe[new_a][new_b]= 'v'

        if dfs(new_a,new_b,r,c):
            return 1
    
    return 0

r, c = map(int, input().split())
pipe = []
for i in range(r):
    pipe.append(list(input()))

cnt = 0
move = [-1,0,1]

for i in range(r):
    cnt += dfs(i,0,r,c)

print(cnt)