# -*- coding: utf-8 -*-
"""BOJ_1806.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xORzwg8bww98joT-Wn0JuHCnkjebsOcv
"""

n, s = map(int, input().split())
a = list(map(int,input().split())) # n개

end = 0
sum_list = 0
min_cnt = n
cnt = 0

for i in range(n):
    while sum_list < s  and end < n:
        sum_list += a[end]
        end +=1
    if sum_list >= s :
        cnt = 1
        if min_cnt > (end-i):
            min_cnt = (end-i)
    sum_list -= a[i]
if cnt != 1:
    print('0')
else:
    print(min_cnt)