# -*- coding: utf-8 -*-
"""BOJ_1789.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18RmcRz6Wz-Gwd40cufn4BaYtjU6OyG9P
"""

s = int(input())
sum_n = 0
i = 0
while s >= sum_n:
    i += 1
    sum_n += i

print(i-1)

import sys
input = sys.stdin.readline

s = int(input())
left = 1
right = s
while left <= right:
    mid = left + (right-left)//2
    if (mid *(mid + 1) // 2) > s:
        right = mid - 1
    else:
        left = mid +1
        ans = mid

print(ans)