# -*- coding: utf-8 -*-
"""BOJ_1175.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_8PClT14OmVCE1H2wJlsm88Kb9lbRcw0
"""

import collections
import sys
input = sys.stdin.readline

def bfs(x,y):
    cnt = 0
    c = e = 0
    Q = collections.deque()
    Q.append([x,y,-1,c,e])

    while Q:
        for _ in range(len(Q)):
            x, y, d, c, e = Q.popleft()

            for i in range(4):
                if i != d:
                    new_x = x + move[0][i]
                    new_y = y + move[1][i]
                    new_c = c
                    new_e = e
                    if 0 <= new_x < n and 0<= new_y < m and table[new_x][new_y] != '#' and  visit[new_x][new_y][i][new_c][new_e] == 0:
                        if table[new_x][new_y] == 'C':
                            new_c = 1

                        elif table[new_x][new_y] == 'E':
                            new_e = 1

                        if new_c == 1 and new_e == 1:
                            return cnt + 1
                        else:
                            visit[new_x][new_y][i][new_c][new_e] = 1
                            Q.append([new_x,new_y,i,new_c,new_e])
        cnt += 1
    return -1
    
n, m = map(int, input().split())
table = []
visit = [[[[[0 for _ in range(2)] for _ in range(2)] for _ in range(4)] for _ in range(m)] for _ in range(n)]

for i in range(n):
    table.append(list(input()))

f = 0
for i in range(n):
    for j in range(m):
        if table[i][j] == 'C':
            table[i][j] = 'E'
            f = 1
            break
    if f:
        break

move = [[0,0,1,-1],[1,-1,0,0]]

for i in range(n):
    for j in range(m):
        if table[i][j] == 'S':
            r = bfs(i,j)
            print(r)
            sys.exit(0)