# -*- coding: utf-8 -*-
"""BOJ_1654.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oyuvAvQjryEqivhX3_RJil3tOGUGUGA7
"""

k, n = map(int,input().split())
a = []
for i in range(k):
    a.append(int(input()))

left = 1
right = max(a)

while left <= right:
    mid = left + (right - left) // 2
    total = 0
    for i in a:
        total += i//mid
    if total < n:
        right = mid-1
    else:
        left = mid+1

print(left-1)