# -*- coding: utf-8 -*-
"""BOJ_2460.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IzJ8l3z8Jryb6CX2F3SvKsrhMEfeT9YG
"""

max = 0
now = 0
for i in range(10):
    out, in_ = map(int, input().split())
    now += in_ - out
    if now > max:
        max = now
    
print(max)