# -*- coding: utf-8 -*-
"""BOJ_2891.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AIQgA02WBMTZLvamBaN-vWm3udH-HSZD
"""

import sys

n, s, r = map(int, input().split())
broken_team = list(map(int, input().split()))
more_team = list(map(int,input().split()))
kayak = [0] + [1]*n 
for i in broken_team:
    kayak[i] -= 1
for i in more_team:
    kayak[i] += 1

cnt = 0
for i in range(1,n):
    if kayak[i] == 0:
        if kayak[i-1] > 1:
            kayak[i-1] -= 1
            kayak[i] += 1 
        elif kayak[i+1] > 1:
            kayak[i+1] -= 1
            kayak[i] += 1

if kayak[n] == 0:
    if kayak[n-1] > 1:
        kayak[n-1] -= 1
        kayak[n] += 1

print(kayak.count(0)-1)