# -*- coding: utf-8 -*-
"""BOJ_3079.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UuIoppZHqcQwucerYmR6jXLm_krh1p7u
"""

import sys
# input = sys.stdin.readline

n , m = map(int, input().split())
t = []
for i in range(n):
    t.append(int(input()))
 

left = min(t)
result = right = max(t) * m

while left <= right:
    mid = left + (right-left) //2 
    total = 0
    for time in t:
        total += mid // time # mid 시간 안에 몇명을 검사할 수 있는지
    if total >= m :
        right = mid -1
        result = min(result, mid)
    else:
        left = mid +1
print(result)