# -*- coding: utf-8 -*-
"""BOJ_2512.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19fAVS_ul5pc2oGHVxI8f7ABud0LcGLx4
"""

import sys
import bisect
input = sys.stdin.readline

n = int(input())
budget = sorted(list(map(int, input().split())))
m = int(input())

result = left = m // n
right = budget[-1]

if sum(budget) <= m:
    print(right)
    sys.exit(0)

while left <= right:
    mid = left + (right-left)//2

    index = bisect.bisect_right(budget,mid)
    t = sum(budget[:index])+ mid *(n-index)

    if t > m :
        right = mid-1
    else:
        result = max(mid,result)
        left = mid +1

print(result)