# -*- coding: utf-8 -*-
"""BOJ_3460.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NdrSMqjFX6B79XpfY-ZbJlrjml8fVsIh
"""

T = int(input())

for _ in range(T):
    n = int(input())
    if n == 1:
        print(0)
        continue 
    i = 0
    while True:
        if n % 2 == 1:
            print(i, end= ' ')
        n = n // 2 
        i +=1
        if n == 1:
            print(i, end='')
            print()
            break

T = int(input())

for _ in range(T):
    B = f'{int(input()):2b}'[::-1]
    print(B)

T = int(input())

for _ in range(T):
    a = str(bin(int(input())))[2:][::-1]
    print(a)
    b = (i for i in range(len(a)) if a[i] == '1')
    print(*b)

))