# -*- coding: utf-8 -*-
"""BOJ_2141.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QoUQBde5B_zwDpeKd6vrJbQ1bu-VNAQS
"""

n = int(input())
town = []
for _ in range(n):
    town.append(list(map(int, input().split())))

town.sort()
total = 0
for i,j in town:
    total += j

mid = total // 2

if total %2 == 1:
    mid += 1

count = 0 
for i,j in town:
    count += j
    if count >= mid:
        print(i)
        break