# -*- coding: utf-8 -*-
"""BOJ_2501.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fii1AA_V1tuULuvR2HE_5tgd_gwTCBvW
"""

N, K = map(int, input().split())
d = [i for i in range(1,N+1) if N % i == 0]
print(0 if len(d)<=K-1 else d[K-1])