# -*- coding: utf-8 -*-
"""BOJ_5014.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N0j8C2XIrQpfXbi88ESssttQIWnR3lOu
"""

from collections import deque

f,s,g,u,d = map(int, input().split())
building = [1000000]*(f+1)
q = deque()

def bfs(x):
    q.append(x)
    building[x] = 0

    while q :
        x = q.popleft()
        if x+u <= f :
            if building[x+u] > building[x]+1 :
                building[x+u] = building[x]+1
                q.append(x+u)
   
        if 1 <= x-d :
            if building[x-d] > building[x]+1:
                building[x-d] = building[x]+1
                q.append(x-d) 
    
bfs(s)

if building[g] == 1000000 :
    print('use the stairs') 
else:
    print(building[g])

+