# -*- coding: utf-8 -*-
"""BOJ_1158.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CeleE6fOf1Js_Dl8x0dWviQ_ZjSHXY3h
"""

import sys
input = sys.stdin.readline

n, k = map(int, input().split())

peoples = [i for i in range(1,n+1)]
result = []
i = 0
while peoples:
    i += k-1
    i %= len(peoples)
    result.append(peoples.pop(i))

print('<',end='')
print(*result, sep = ', ', end= '')
print('>')

