# -*- coding: utf-8 -*-
"""BOJ_2503.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10SWlJeMepml4jxoOQE2zvdZxX9WHNiy9
"""

import itertools
N = int(input()) 

can = list(itertools.permutations([1,2,3,4,5,6,7,8,9], 3))

for _ in range(N):
    number, strike, ball = map(int, input().split())
    num_list = list(str(number))
    cnt = 0

    for i in range(len(can)):
        s_cnt = 0
        b_cnt = 0
        i -= cnt

        for j in range(3):
            num = int(num_list[j])
            if num in can[i]:
                if j == can[i].index(num):
                    s_cnt += 1
                else:
                    b_cnt += 1

        if s_cnt != strike or b_cnt != ball:
            can.remove(can[i])
            cnt += 1

print(len(can))