# -*- coding: utf-8 -*-
"""BOJ_11404.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GpzzR9Z4aO3u1u7kIeoIGHLo5kuOgFXT
"""

import sys
max_value = sys.maxsize

# 도시의 개수
n = int(input())

graph = [[max_value]*n for _ in range(n)]
for i in range(n):
    graph[i][i] = 0
# 버스의 개수
m = int(input())

for i in range(m):
    a, b, c = map(int, input().split())
    graph[a-1][b-1] = min(c, graph[a-1][b-1])

for k in range(n):
    for i in range(n):
        for j in range(n):
            graph[i][j] = min(graph[i][j], graph[i][k]+graph[k][j])

for i in range(n):
    for j in range(n):
        if graph[i][j] != max_value:
            print(graph[i][j], end=' ')
        else:
            print(0, end=' ')
    print()