# -*- coding: utf-8 -*-
"""BOJ_1292.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_-a6bR5KA2NJaPF-gjs_YViejcuoW5rS
"""

start, end = map(int, input().split())
L = [0]
i = 1
while len(L) <= end:
    for j in range(i):
        L.append(i+L[-1])
    i += 1

print(L[end]-L[start-1])

start, end = map(int, input().split())
L = []
i = 1
while len(L) < end:
    for j in range(i):
        L.append(i)
    i += 1

print(sum(L[start-1:end]))