# -*- coding: utf-8 -*-
"""BOJ_3197

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sM71Ict1cjZfll3-a8SXmt0J6l5YAU7D
"""

import collections
import sys
input = sys.stdin.readline

def melt(r,c):
    while water:
        i, j = water.popleft()
        for k in range(4):
            new_i = i + move[0][k]
            new_j = j + move[1][k]
            if 0 <= new_i < r and 0 <= new_j < c and lake[new_i][new_j] == 'X':
                lake[new_i][new_j] = '.'
                next_water.append([new_i,new_j])

def meet(r,c):
    while swan:
        x, y = swan.popleft()
        for k in range(4):
            new_x = x + move[0][k]
            new_y = y + move[1][k]
            if 0 <= new_x < r and 0 <= new_y < c  and visited[new_x][new_y]==0:
                if lake[new_x][new_y] == '.':
                    visited[new_x][new_y] = 1
                    swan.append([new_x,new_y])
                elif lake[new_x][new_y] == 'L':
                    visited[new_x][new_y] = 1
                    return 1
                elif lake[new_x][new_y] == 'X':
                    visited[new_x][new_y] = 1
                    next_swan.append([new_x,new_y])
    return 0

r , c = map(int, input().split())
move = [[0,0,1,-1],[1,-1,0,0]]

lake = []
swan = collections.deque()
next_swan = []
water = collections.deque()
next_water = []
f = 1
for i in range(r):
    tmp = list(input())
    for j in range(c):
        if tmp[j] == 'L':
            if f:
                swan.append([i,j])
                f = 0
            water.append([i,j])
            
        elif tmp[j] == '.':
            water.append([i,j])
    lake.append(tmp)

visited = [[0 for _ in range(c)]for _ in range(r)]
visited[swan[0][0]][swan[0][1]] = 1

cnt = 0
while True:
    if meet(r,c):
        print(cnt)
        break
    melt(r,c)

    swan = [i[:] for i in next_swan]
    water = [i[:] for i in next_water]
    swan = collections.deque(swan)
    water = collections.deque(water)
    
    next_swan.clear()
    next_water.clear()
    cnt += 1