# -*- coding: utf-8 -*-
"""BOJ_10816.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XiRy5F5954Tu3MWahKbPk_mHUi45Lg6q
"""

import collections
n = int(input())
a = list(map(int, input().split()))
m = int(input())
b = list(map(int, input().split()))

nums = collections.Counter(a)
print(nums)

for i in b:
    if nums[i]:
        print(nums[i], end = ' ')
    else:
        print(0, end= ' ')