# -*- coding: utf-8 -*-
"""BOJ_1700.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-SyxkNaqjBLgJRU64brxTh7tyd2NdkrX
"""

n , k = map(int, input().split())
a = list(map(int, input().split()))

cnt = 0
c = [0] * n

for i in range(k):
    if a[i] in c:
        continue

    if 0 in c:
        c[c.index(0)] = a[i]
        continue    
    tmp = 0
    for j in range(n):
        if c[j] in a[i+1:]:
            if tmp <= a[i+1:].index(c[j]):
                tmp = a[i+1:].index(c[j])
                tmp_idx = j    
        else:
            tmp = 101
            tmp_idx = j  
    c[tmp_idx] = a[i]
    print(c)
    cnt +=1
    
print(cnt)