# -*- coding: utf-8 -*-
"""BOJ_15685.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qzYlCz5axBdZTKmoXvNa9K3841gUOJpK
"""

n = int(input())
whole = [[0 for _ in range(101)] for _ in range(101)]

for _ in range(n):
    x,y,d,g = map(int, input().split())

    dragon = [[x,y]]
    direction = [d]
    end = [x,y]
    for i in range(g+1):
        if i == 0:
            r = -1
        else:
            r = 0
        for j in range(len(direction)-1,r,-1):
            a,b = dragon[-1]
            now_d = direction[j]

            if now_d == 0:
                new_a = a+1
                new_b = b
            elif now_d == 1:
                new_a = a
                new_b = b-1
            elif now_d == 2:
                new_a = a-1
                new_b = b
            elif now_d == 3:
                new_a = a
                new_b = b+1

            if 0 <= new_a <= 100 and 0 <= new_b <= 100:
                dragon.append([new_a,new_b])
                new_d = (now_d + 1) % 4
                direction.append(new_d)                

    for r,c in dragon:
        whole[r][c] = 1

cnt = 0
for i in range(100):
    for j in range(100):
        if whole[i][j] == 1 and whole[i+1][j] == 1 and whole[i][j+1] == 1 and whole[i+1][j+1] == 1:
            cnt +=1

print(cnt)