# -*- coding: utf-8 -*-
"""BOJ_1613.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i8t3e5j7PZxE8__cnSc42Lftp55-5blg
"""

import sys
input = sys.stdin.readline
max_val = 50001

n, k = map(int, input().split())

graph = [[max_val for _ in range(n+1)]for _ in range(n+1)]

for i in range(1,n+1):
    graph[i][i] = 0

for i in range(k):
    a, b = map(int, input().split())
    graph[a][b] = 1

for k in range(1,n+1):
    for i in range(1,n+1):
        for j in range(1,n+1):
            graph[i][j] = min(graph[i][j], graph[i][k] + graph[k][j])

s = int(input())
for i in range(s):
    a, b = map(int, input().split())
    if graph[a][b] == max_val and graph[b][a] == max_val:
        print(0)
    elif graph[a][b] == max_val and graph[b][a] != max_val:
        print(1)
    elif graph[a][b] != max_val and graph[b][a] == max_val:
        print(-1)