# -*- coding: utf-8 -*-
"""BOJ_1978.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Kp1PtnTIxd6a6Pbrhy4a4PsapdF73o6a
"""

n = int(input())
a = list(map(int,input().split()))
count = 0

for i in a:
    tmp = 0
    flag = True
    if i == 1:
        pass
    elif i == 2:
        count+=1    
    else:
        for j in range(2,i):
            if i % j == 0:
                flag = False
                break
        if flag:
            count+= 1        
print(count)