# -*- coding: utf-8 -*-
"""BOJ_10775.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XpgJqnICi8TELZQfSUmIGbIt4h5vDt6O
"""

def find(x):
    if parent[x] == x:
        return x
    else:
        parent[x] = find(parent[x])
        return parent[x]

g = int(input())
p = int(input())

parent = {i:i for i in range(g+1)}

airplane = []
for _ in range(p):
    n = int(input())
    airplane.append(n)

cnt = 0
for n in airplane:
    p = find(n)
    if p == 0:
        break
    parent[p] = p-1
    cnt +=1
    
print(cnt)