# -*- coding: utf-8 -*-
"""BOJ_14889.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11GeDSn0gZdybD9r9d8QpoOSnrgFwxNDb
"""

import itertools
import sys
min_result= sys.maxsize

n = int(input())
numbers = [i for i in range(1,n+1)]
table = []
for _ in range(n):
    table.append(list(map(int, input().split())))

combinations = list(itertools.combinations(numbers, n//2))
print(combinations)
for c in range(n//2):
    left_combi = list(itertools.permutions(combinations[i],2))
    right_combi = list(itertools.permutions(combinations[-i-1],2))
    sum_left = 0
    sum_right = 0
    for i, j in left_combi:
        sum_left += table[i][j]
    for i, j in right_combi:
        sum_right += table[i][j]

    result = abs(sum_left - sum_right)
    if min_result > result:
        min_result = result

print(min_result)

n = 6
numbers = [i for i in range(1,n+1)]
combinations = list(itertools.combinations(numbers, n//2))
for i in combinations:
    print(i)

